name: Build OnePlus Ace2Pro Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex git libssl-dev \
          libelf-dev libncurses-dev openjdk-11-jdk unzip xz-utils repo python3 python3-pip

    - name: Sync kernel sources
      run: |
        mkdir kernel && cd kernel
        repo init -u https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550.git
        cp ../oneplus_ace2pro_v.xml .repo/manifests/
        repo init -m oneplus_ace2pro_v.xml
        repo sync -j2 --force-sync

    - name: Build kernel
      run: |
        cd kernel/kernel_platform/msm-kernel
        mkdir -p out
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        export CLANG_PATH=$(pwd)/../../prebuilts/clang/host/linux-x86/clang-r*/bin
        export PATH=$CLANG_PATH:$PATH
        make O=out oneplus_sm8550_defconfig
        make -j2 O=out

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: kernel-out
        path: kernel/kernel_platform/msm-kernel/out/arch/arm64/boot/
