name: Build OnePlus Ace2Pro Kernel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu‑latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex git \
          libssl-dev libelf-dev libncurses-dev openjdk-11-jdk unzip xz-utils \
          python3 python3-pip repo clang xz-utils

    - name: Sync kernel sources
      run: |
        mkdir kernel && cd kernel
        repo init -u https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550.git
        cp ../oneplus_ace2pro_v.xml .repo/manifests/
        repo init -m oneplus_ace2pro_v.xml
        repo sync -j$(nproc) --force-sync

    - name: Build kernel
      run: |
        cd kernel/kernel_platform/msm-kernel
        mkdir -p out
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        export CLANG_PATH=$(pwd)/../../prebuilts/clang/host/linux-x86/clang-*/
        export PATH=$CLANG_PATH:$PATH
        make O=out oneplus_sm8550_defconfig
        make -j$(nproc) O=out

    - name: Package via AnyKernel3
      run: |
        cd ../../..  # 回到仓库根目录
        zip -r kernel.zip zipper/AnyKernel3/*  # 假设模板已放入 zipper/AnyKernel3
        # 放 kernel/out 文件到模板里
        cp kernel/kernel_platform/msm-kernel/out/arch/arm64/boot/Image.gz zipper/AnyKernel3/
        cd zipper/AnyKernel3
        zip -r ../ace2pro-kernel.zip *

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ace2pro-kernel
        path: |
          kernel/kernel_platform/msm-kernel/out/arch/arm64/boot/
          zipper/ace2pro-kernel.zip
